// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import NavbarBrasa from "@/components/custom/navbar-brasa";
import WhatsAppButton from "@/components/custom/whatsapp-button-brasa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sushi Brasa - Comida Japonesa Premium",
  description: "Sushi artesanal com toque de brasa. Peça agora e receba em casa!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <NavbarBrasa />
        <main className="min-h-screen">
          {children}
        </main>
        <WhatsAppButton />
      </body>
    </html>
  );
}
